apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-card-deployment
  namespace: packapp04
spec:
  selector:
    matchLabels:
      app: back-card
  replicas: 1
  template:
    metadata:
      labels:
        app: back-card
    spec:
      containers:
      - name: back-card
        image: registry.hackathon-container.com/packapp04/back-card:2.1
        ports:
        - containerPort: 9093
      imagePullSecrets:
      - name: registry
---
apiVersion: v1
kind: Service
metadata:
  name: back-card-svc
  namespace: packapp04
spec:
  type: ClusterIP
  selector:
    app: back-customer
  ports:
  - name: back-card-ports 
    port: 9093
    targetPort: 9093
    protocol: TCP
